import { CyberCard } from "@/components/CyberCard";
import { Shield, Lock, FileText, CheckCircle, Database, Server } from "lucide-react";

export default function Security() {
  return (
    <div className="container mx-auto px-4 py-24 max-w-4xl">
      <div className="text-center mb-16">
        <h1 className="text-5xl font-black font-heading text-accent mb-6 leading-none">SECURITY MODEL</h1>
        <p className="font-mono text-muted-foreground text-lg uppercase tracking-widest">WAVE 1 HARDENING ACTIVE</p>
      </div>

      <div className="space-y-8">
        <CyberCard title="CRYPTOGRAPHIC FOUNDATION">
          <div className="flex gap-6 items-start">
            <Shield className="w-12 h-12 text-accent shrink-0" />
            <div className="space-y-4">
              <h3 className="text-xl font-bold text-white uppercase tracking-tighter">secp256k1 Transaction Signing</h3>
              <p className="font-mono text-sm text-muted-foreground leading-relaxed">
                WebDollar 2 uses standard secp256k1 elliptic curve cryptography for wallet generation and transaction integrity. 
                Every transfer requires a unique cryptographic signature generated by your locally-decrypted private key. 
                The server validates this signature against your public key using deterministic verification—replaying transactions is mathematically impossible.
              </p>
            </div>
          </div>
        </CyberCard>

        <CyberCard title="SESSION INTEGRITY">
          <div className="flex gap-6 items-start">
            <Lock className="w-12 h-12 text-primary shrink-0" />
            <div className="space-y-4">
              <h3 className="text-xl font-bold text-white uppercase tracking-tighter">Persistent Database Sessions</h3>
              <p className="font-mono text-sm text-muted-foreground leading-relaxed">
                Unlike experimental platforms that use transient MemoryStore, WebDollar 2 utilizes a production-grade PostgreSQL session store. 
                This ensures that your authentication context is isolated, persistent, and verifiable across server scaling and reboots. 
                We enforce strict SameSite=None and Secure cookie flags for cross-domain ecosystem security.
              </p>
            </div>
          </div>
        </CyberCard>

        <CyberCard title="CONCENSUS ISOLATION">
          <div className="flex gap-6 items-start">
            <Server className="w-12 h-12 text-accent shrink-0" />
            <div className="space-y-4">
              <h3 className="text-xl font-bold text-white uppercase tracking-tighter">Single Execution Context</h3>
              <p className="font-mono text-sm text-muted-foreground leading-relaxed">
                For mining and staking integrity, the application enforces a "Single Active Tab" policy. 
                This prevents multi-context race conditions in the DIELBS consensus engine and ensures your private keys 
                are never handled by multiple browser threads concurrently, preventing accidental key leaks.
              </p>
            </div>
          </div>
        </CyberCard>

        <div className="bg-accent/5 border border-accent/20 p-8 rounded-md text-center">
            <h4 className="text-accent font-bold mb-4 uppercase tracking-[0.3em]">Auditor Verification</h4>
            <p className="text-xs font-mono text-muted-foreground">
                WebDollar 2 has undergone initial internal audit sweeps. 
                The current build (Wave 1) satisfies requirements for Content Security Policy (CSP), Session Protection, 
                and Input Validation (Zod). All sensitive server-side logging is disabled in the production environment.
            </p>
        </div>
      </div>
    </div>
  );
}
